#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
# I Love you Ding Li！ I will love you forever!
# *2020-12-08*
#

PROJECT_NAME := http_client_app

include $(IDF_PATH)/make/project.mk

